version:  '3.2'

networks:
    php: ~
    proxy:
        external:
            name: dev_proxy
    db:
        external:
            name: dev_database
    maildev:
        external:
            name: dev_maildev
    memcached:
        external:
            name: dev_memcached

services:
    php:
        image: lephare/php:7.1
        user: "${UID:-1000}:${GID:-1000}"
        networks:
            php: ~
            db: ~
            memcached: ~
            maildev: ~
        volumes:
            - .:/var/www/symfony
            - $HOME/.composer:/var/tmp/composer
        environment:
            SYMFONY_ENV: dev

    web:
        image: lephare/apache:2.4
        networks:
            php: ~
            proxy:
                aliases:
                    - numerology.$DOCKER_HOST_SUFFIX
        depends_on:
            - php
        volumes:
            - .:/var/www/symfony
            - ./var/logs/apache:/var/log/apache2
        environment:
            VIRTUAL_HOST: numerology.$DOCKER_HOST_SUFFIX
            CERT_NAME: generic

    node:
        image: node:alpine
        volumes:
            - .:/var/www/symfony
        user: 1000:1000
        working_dir: /var/www/symfony
