<?php

namespace AppBundle\Repository;

/**
 * NumerologieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NumerologieRepository extends \Doctrine\ORM\EntityRepository
{
}
