site:
    resource: "@SiteBundle/Resources/config/routing.yml"
    prefix:   /

extranet:
    resource: '@ExtranetBundle/Resources/config/routing.yml'
    prefix: /extranet

fos_js_routing:
   resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
