security:
    providers:
        hwi:
            id: ExtranetBundle\Security\UserProvider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured_area:
            anonymous: ~
            oauth:
                resource_owners:
                    auth0: "/extranet/auth0/callback"
                login_path:        /extranet/login
                use_forward:       false
                failure_path:      /extranet/login

                oauth_user_provider:
                    service: ExtranetBundle\Security\UserProvider
            logout:
                path:   /extranet/auth0/logout
                target: /extranet/

    access_control:
        # Extranet
        - { path: ^/extranet/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/extranet/connect, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/extranet/, roles: ROLE_EXTRANET_LOGIN }
        - { path: ^/extranet/admin/, roles: ROLE_ADMIN_LOGIN }

        # Site
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }

    role_hierarchy:
        ROLE_ADMIN:
            - ROLE_ADMIN_LOGIN
            - ROLE_USER

        ROLE_USER:
            - ROLE_EXTRANET_LOGIN
            - ROLE_MESSAGE
            - ROLE_ANALYSIS

        ROLE_DEMO:
            - ROLE_EXTRANET_LOGIN
            - ROLE_MESSAGE
            - ROLE_ANALYSIS_SHOW
            - ROLE_ANALYSIS_EXPORT

        ROLE_MESSAGE:
            - ROLE_MESSAGE_READ
            - ROLE_MESSAGE_WRITE

        ROLE_ANALYSIS:
            - ROLE_ANALYSIS_HISTORY
            - ROLE_ANALYSIS_SHOW
            - ROLE_ANALYSIS_EDIT
            - ROLE_ANALYSIS_ADD
            - ROLE_ANALYSIS_DELETE
            - ROLE_ANALYSIS_EXPORT
            - ROLE_ANALYSIS_COMPARE
