security:
    providers:
        hwi:
            id: AppBundle\Security\UserProvider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured_area:
            anonymous: ~
            oauth:
                resource_owners:
                    auth0: "/extranet/auth0/callback"
                login_path:        /extranet/login
                use_forward:       false
                failure_path:      /extranet/login

                oauth_user_provider:
                    service: AppBundle\Security\UserProvider
            logout:
                path:   /extranet/auth0/logout
                target: /extranet/

    access_control:
        - { path: ^/extranet/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/extranet/connect, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_USER }