extranet_index:
  path: /
  defaults: { _controller: ExtranetBundle:Analysis:index }

extranet_add:
    path: /ajouter/
    defaults: { _controller: ExtranetBundle:Analysis:add }
    options:
        expose: true

extranet_edit:
    path: /editer/{hash}
    defaults: { _controller: ExtranetBundle:Analysis:edit }

extranet_delete:
    path: /supprimer/{hash}
    defaults: { _controller: ExtranetBundle:Analysis:supprimer }

extranet_export_pdf:
    path: /exporter/pdf/{hash}
    defaults: { _controller: ExtranetBundle:Analysis:exportPdf }

extranet_show:
    path: /afficher/{hash}
    defaults: { _controller: ExtranetBundle:Analysis:show }

admin_index:
    path: /administrer/
    defaults: { _controller: ExtranetBundle:Admin:index }

admin_users_list:
    path: /administrer/utilisateurs/
    defaults: { _controller: ExtranetBundle:Admin:usersList }

admin_user_validate:
    path: /administrer/utilisateur/valider/{userId}
    defaults: { _controller: ExtranetBundle:Admin:userValidate }
    options:
        expose: true

admin_user_refuse:
    path: /administrer/utilisateur/refuser/{userId}
    defaults: { _controller: ExtranetBundle:Admin:userRefuse }
    options:
        expose: true

admin_numbers_list:
    path: /administrer/numeros/
    defaults: { _controller: ExtranetBundle:Admin:numbersList }

admin_number_edit:
    path: /administrer/numero/{id}
    defaults: { _controller: ExtranetBundle:Admin:numberEdit }

admin_definitions_list:
    path: /administrer/definitions/
    defaults: { _controller: ExtranetBundle:Admin:definitionsList }

admin_definition_edit:
    path: /administrer/definition/{id}
    defaults: { _controller: ExtranetBundle:Admin:definitionEdit }

messages_number:
    path: /messages/tous/total/
    defaults: { _controller: ExtranetBundle:Messages:getMessagesNumber }
    options:
        expose: true

messages_list:
    path: /messages/tous/
    defaults: { _controller: ExtranetBundle:Messages:getMessages }
    options:
        expose: true

messages_show:
    path: /messages/afficher/
    defaults: { _controller: ExtranetBundle:Messages:showMessages }
    options:
        expose: true

messages_send:
    path: /messages/envoyer/
    defaults: { _controller: ExtranetBundle:Messages:sendMessage }
    options:
        expose: true

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /login

auth0_login:
    path:    /auth0/callback

auth0_logout:
    path: /auth0/logout