site_homepage:
    path:     /
    defaults: { _controller: SiteBundle:Default:homepage }

site_try:
    path:     /essayer
    defaults: { _controller: SiteBundle:Default:try }

site_show:
    path:     /resultats
    defaults: { _controller: SiteBundle:Default:show }
