site_homepage:
    path:     /
    defaults: { _controller: SiteBundle:Default:homepage }

site_try:
    path:     /essayer
    defaults: { _controller: SiteBundle:Default:try }

site_show_free:
    path:     /resultats/{hash}
    defaults: { _controller: SiteBundle:Default:show }

site_show_details:
    path:     /resultats/{hash}/details
    defaults: { _controller: SiteBundle:Default:showDetails }
    options:
        expose: true

site_contact:
    path:     /contact
    defaults: { _controller: SiteBundle:Default:contact }