site_homepage:
    path:     /
    defaults: { _controller: SiteBundle:Default:homepage }

site_try:
    path:     /essayer/{version}
    defaults: { _controller: SiteBundle:Default:try }

site_show:
    path:     /resultats/{hash}
    defaults: { _controller: SiteBundle:Default:show }

site_edit:
    path:     /editer/{hash}
    defaults: { _controller: SiteBundle:Default:edit }

site_show_details:
    path:     /resultats/{hash}/details
    defaults: { _controller: SiteBundle:Default:showDetails }
    options:
        expose: true

site_export_pdf:
    path:     /exporter/{hash}
    defaults: { _controller: SiteBundle:Default:exportPdf }

site_contact:
    path:     /contact
    defaults: { _controller: SiteBundle:Default:contact }