numerologie_index:
  path: /
  defaults: { _controller: AppBundle:Numerologie:index }

numerologie_add:
    path: /ajouter/
    defaults: { _controller: AppBundle:Numerologie:add }
    options:
        expose: true

numerologie_edit:
    path: /editer/{md5}
    defaults: { _controller: AppBundle:Numerologie:edit }

numerologie_delete:
    path: /supprimer/{md5}
    defaults: { _controller: AppBundle:Numerologie:supprimer }

numerologie_export_pdf:
    path: /exporter/pdf/{md5}
    defaults: { _controller: AppBundle:Numerologie:exportPdf }

numerologie_show:
    path: /afficher/
    defaults: { _controller: AppBundle:Numerologie:show }

admin_index:
    path: /administrer/
    defaults: { _controller: AppBundle:Admin:index }

admin_user_validate:
    path: /administrer/utilisateur/valider/{userId}
    defaults: { _controller: AppBundle:Admin:userValidate }
    options:
        expose: true

admin_user_refuse:
    path: /administrer/utilisateur/refuser/{userId}
    defaults: { _controller: AppBundle:Admin:userRefuse }
    options:
        expose: true

messages_number:
    path: /messages/tous/total/
    defaults: { _controller: AppBundle:Messages:getMessagesNumber }
    options:
        expose: true

messages_list:
    path: /messages/tous/
    defaults: { _controller: AppBundle:Messages:getMessages }
    options:
        expose: true

messages_show:
    path: /messages/afficher/
    defaults: { _controller: AppBundle:Messages:showMessages }
    options:
        expose: true

messages_send:
    path: /messages/envoyer/
    defaults: { _controller: AppBundle:Messages:sendMessage }
    options:
        expose: true
