numerologie_index:
  path: /
  defaults: { _controller: AppBundle:Numerologie:index }

numerologie_add:
    path: /ajouter/
    defaults: { _controller: AppBundle:Numerologie:add }

numerologie_show:
    path: /afficher/
    defaults: { _controller: AppBundle:Numerologie:show }

numerologie_admin:
    path: /administrer/
    defaults: { _controller: AppBundle:Admin:index }

numerologie_admin_user_validate:
    path: /administrer/utilisateur/valider/{userId}
    defaults: { _controller: AppBundle:Admin:userValidate }
    options:
        expose: true

numerologie_admin_user_refuse:
    path: /administrer/utilisateur/refuser/{userId}
    defaults: { _controller: AppBundle:Admin:userRefuse }
    options:
        expose: true