numerologie_index:
  path: /
  defaults: { _controller: AppBundle:Numerologie:index }

numerologie_add:
    path: /ajouter
    defaults: { _controller: AppBundle:Numerologie:add }

numerologie_show:
    path: /afficher/
    defaults: { _controller: AppBundle:Numerologie:show }
